# Main 데이터베이스 설정 (H2 Database)
main:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testdb
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000
      max-life-time: 300000

  # JPA 설정
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
